development:
  adapter: postgresql
  database: delayjobstest
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: my_database_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: delayjobstest
  pool: 5
  timeout: 5000