# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0332e9acbed1fa620855dabd6ffe8d94d1fa3ce4a4cddcff6a083085571ddbfb4237073ce7d7aae4f384c73eadfe7b767ffa445f89e25f97705a83aa1130bda

test:
  secret_key_base: 3d1c3d08a7436e0638785d42f175495f9107382c9cd8492fce3583d9b8c815a663f88f80809b527947079d034f6a6f8eee98186d938d27b155faa5facfbad86f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: a0332e9acEEEE20855dabd6ffe8d94d1fa3ce4a4cddcff6a083085571ddbfb4237073ce7d7aae4f384c73eadfe7b767ffa445f89e25f97705a83aa1130bda
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
